name: vrc-slide-server
version: 0.1.0
synopsis: A slide server for VRC_Panorama
description: Please see README.md
maintainer: haru2036
github: vrc-lt/VRC-Slide-Server
category: Web
extra-source-files: []

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - Spock >= 0.11
  - mtl
  - text

executable:
  main: Main.hs
  source-dirs: app
  dependencies: []