name: vrc-slide-server
version: 0.1.0
synopsis: hoge
description: piyo
maintainer: haru2036
github: TBD
category: Web
extra-source-files: []

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - Spock >= 0.11
  - mtl
  - text

executable:
  main: Main.hs
  source-dirs: app
  dependencies: []

tests:
  spec:
    defaults: hspec/hspec@master
