apiVersion: v1
kind: Service
metadata:
  name: vrc-slide-server
spec:
  selector:
    app: vrc-slide-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
